//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disco
    {
        public int IdDisco { get; set; }
        public string Titulo { get; set; }
        public double Duracion { get; set; }
        public int Anio { get; set; }
        public string GeneroMusical { get; set; }
        public Nullable<int> IdDistribuidora { get; set; }
        public Nullable<int> IdArtista { get; set; }
        public Nullable<int> Disponibilidad { get; set; }
        public Nullable<int> Ventas { get; set; }
    
        public virtual Artista Artista { get; set; }
        public virtual Distribuidora Distribuidora { get; set; }
    }
}
